publish commit

diff --git a/fat b/fat
--- a/fat
+++ b/fat
@@ -4,6 +4,8 @@ out() { printf '\033[1;34m-> \033[m%s\n' "$@" >&2 ;}
 error() { printf '\033[1;31m!> \033[m%s\n' "$@" >&2 ;}
 die() { printf '\033[1;31m!> \033[m%s\n' "$@" >&2 ; exit 1 ;}
 
+cache_dir="$KISS_ROOT${XDG_CACHE_HOME:-$HOME/.cache}/fat"
+
 usage() {
     out "fat [g|i|s|u|v] [pkg] [pkg] [pkg]" \
         "get:         Install package from the given url" \
@@ -17,47 +19,47 @@ usage() {
 fn_update() {
     [ "$FAT_PATH" ] || die "Please add \$FAT_PATH to your environment before updating"
     out "Getting the latest manifest"
-    mkdir -p "$HOME/.cache/fat/manifest"
-    rm -f "$HOME/.cache/fat/manifest/"*
-    :> "$HOME/.cache/fat/manifest/list"
+    mkdir -p "$cache_dir/manifest"
+    rm -f "$cache_dir/manifest/"*
+    :> "$cache_dir/manifest/list"
     for dist in $(echo "$FAT_PATH" | tr ';' ' ') ; do
-        manloc="$HOME/.cache/fat/manifest/$(echo "$dist" | sed -E 's/https?:\/\///g;s/\/.*//g')"
+        manloc="$cache_dir/manifest/$(echo "$dist" | sed -E 's/https?:\/\///g;s/\/.*//g')"
         curl "$dist/manifest" -Lo "$manloc"
-        printf '%s\t%s\n' "$dist" "$manloc" >> "$HOME/.cache/fat/manifest/list"
+        printf '%s\t%s\n' "$dist" "$manloc" >> "$cache_dir/manifest/list"
     done
 }
 
 fn_checkmanifest() {
-    [ -e "$HOME/.cache/fat/manifest/list" ] ||
+    [ -e "$cache_dir/manifest/list" ] ||
         die "Manifest list could not be found, please run" "fat update"
     while IFS="$(printf '\t')" read -r dist manloc ; do
         grep -q "^$1\t" "$manloc" || continue
         pkginfo="$(grep "^$1\t" "$manloc" | sort -V | sed '$!d')"
         export dist pkginfo
         break
-    done < "$HOME/.cache/fat/manifest/list"
+    done < "$cache_dir/manifest/list"
 }
 
 fn_get() {
     prog=1
     for src in "$@" ; do
-        mkdir -p "$HOME/.cache/fat/fat_get"
+        mkdir -p "$cache_dir/fat_get"
         out "Installing ${src##*/} ($prog/$#)"
         out "Downloading from $src"
-        curl "$src" -Lo "$HOME/.cache/fat/manual/${src##*/}" || die "Failed to download package from $src"
+        curl "$src" -Lo "$cache_dir/manual/${src##*/}" || die "Failed to download package from $src"
         out "Installing ${src##*/} through kiss"
-        kiss i "$HOME/.cache/fat/fat_get/${src##*/}" || die "Failed to install ${src##*/}"
+        kiss i "$cache_dir/fat_get/${src##*/}" || die "Failed to install ${src##*/}"
         prog=$(( prog + 1 ))
     done
 }
 
 fn_search() {
-    [ -e "$HOME/.cache/fat/manifest/list" ] ||
+    [ -e "$cache_dir/manifest/list" ] ||
         die "Manifest list could not be found, please run" "fat update"
     while IFS="$(printf '\t')" read -r dist manloc ; do
         out "$dist:"
         grep "^$1\t" "$manloc" | sort -V | sed '$!d' | cut -f 1,2
-    done < "$HOME/.cache/fat/manifest/list"
+    done < "$cache_dir/manifest/list"
 }
 
 fn_install() {
@@ -71,19 +73,38 @@ fn_install() {
         pkgdeps="$(echo "$pkginfo" | cut -f 5)"
 
         for dep in $pkgdeps; do
-            kiss l "$dep" >/dev/null 2>&1 && continue
+            # Skip dependencies if they are already installed.
+            # Can be skipped if FAT_FORCE variable exists.
+            [ "$FAT_FORCE" ] ||
+                { kiss l "$dep" >/dev/null 2>&1 && continue ;}
             fn_install "$dep"
         done
 
         fn_checkmanifest "$pkg" 
         out "Downloading the package"
         pkgdest="$(echo "$pkginfo" | cut -f 3)"
-        pkgloc="$dist/$(echo "$pkginfo" | cut -f 3 | sed 's/#/%23/g' )"
-        echo "$pkgloc"
-        mkdir -p "$HOME/.cache/fat/bin"
-        curl "$pkgloc" -fLo "$HOME/.cache/fat/bin/$pkgdest" ||
+
+        # If the source is https?, change the # to %23
+        case "$dist" in
+            http*://*) pkgloc="$dist/$(echo "$pkginfo" | cut -f 3 | sed 's/#/%23/g' )" ;;
+            *) pkgloc="$dist/$(echo "$pkginfo" | cut -f 3 )" ;;
+        esac
+
+        mkdir -p "$cache_dir/bin"
+
+        curl "$pkgloc" -fLo "$cache_dir/bin/$pkgdest" ||
             die "Could not download the tarball"
-        kiss i "$HOME/.cache/fat/bin/$pkgdest"
+
+        out "Checking sha256sums"
+        [ "$(echo "$pkginfo" | cut -f 4)" = "$(sha256sum "$cache_dir/bin/$pkgdest" | awk '{print $1}')" ] || die "Checksums mismatch"
+
+        out "Checking gpg signature"
+        mkdir -p "$cache_dir/sig"
+        curl "${pkgloc}.asc" -fLo "$cache_dir/sig/${pkgdest}.asc" || die "Could not download signature"
+        gpg --verify "$cache_dir/sig/${pkgdest}.asc" "$cache_dir/bin/$pkgdest"
+
+        out "Installing package with kiss"
+        kiss i "$cache_dir/bin/$pkgdest"
         
     done
 }
@@ -95,7 +116,7 @@ main() {
     case "$prog" in
         g|get) fn_get "$@" ;;
         i|install) fn_install "$@" ;;
-        s|search) fn_search "$@" ;;
+        s|search) fn_search "$1" ;;
         u|update) fn_update "$@" ;;
         v|version) out "fat-0.1.0" ;;
         -h|--help|help|h) usage ;;
